on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2.3.2
     # login not needed if firewall is configured
     - uses: Azure/login@v1
       with:
         creds: ${{secrets.AZURE_CREDENTIALS}}
     - uses: azure/postgresql@v1
       with:
        connection-string: ${{â€¯secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
        server-name: server091625644.postgres.database.azure.com
        plsql-file: "employeedb.sql"
